import React, { useState } from "react";
import { FaPlus, FaPen, FaTrash, FaTimes } from "react-icons/fa";

const ReportsList = () => {
  const [reports, setReports] = useState([
    { reportTitle: "Sales Report - March", date: "2023-03-31", generatedBy: "John Doe", status: "Completed" },
    { reportTitle: "Expenses Report - Q1", date: "2023-04-15", generatedBy: "Jane Smith", status: "In Progress" },
    { reportTitle: "Customer Feedback - 2023", date: "2023-05-01", generatedBy: "Michael Lee", status: "Completed" },
  ]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [newReport, setNewReport] = useState({
    reportTitle: "",
    date: "",
    generatedBy: "",
    status: "",
  });

  const handleInputChange = (e) => {
    setNewReport({ ...newReport, [e.target.name]: e.target.value });
  };

  const handleAddReport = () => {
    if (newReport.reportTitle && newReport.date && newReport.generatedBy && newReport.status) {
      setReports([...reports, newReport]);
      setNewReport({ reportTitle: "", date: "", generatedBy: "", status: "" });
      setIsModalOpen(false);
    } else {
      alert("Please fill all fields!");
    }
  };

  const handleDelete = (index) => {
    const updatedReports = reports.filter((_, i) => i !== index);
    setReports(updatedReports);
  };

  const handleEdit = (index) => {
    const reportToEdit = reports[index];
    setNewReport({ ...reportToEdit });
    setIsModalOpen(true);
    handleDelete(index); // Remove the report to be edited before updating it
  };

  return (
    <div className="p-6 bg-white rounded-lg shadow-lg">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold">Reports List</h2>
        <button
          className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded flex items-center gap-2"
          onClick={() => setIsModalOpen(true)}
        >
          <FaPlus /> Add Report
        </button>
      </div>

      {/* Reports List */}
      <div className="overflow-x-auto">
        <table className="w-full border text-sm">
          <thead className="bg-gray-200">
            <tr>
              <th className="p-3 border text-left">Report Title</th>
              <th className="p-3 border text-left">Date</th>
              <th className="p-3 border text-left">Generated By</th>
              <th className="p-3 border text-left">Status</th>
              <th className="p-3 border text-left">Action</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report, index) => (
              <tr key={index} className="hover:bg-gray-100 border-b">
                <td className="p-3 border">{report.reportTitle}</td>
                <td className="p-3 border">{report.date}</td>
                <td className="p-3 border">{report.generatedBy}</td>
                <td className="p-3 border">{report.status}</td>
                <td className="p-3 border flex gap-3 justify-center">
                  <button onClick={() => handleEdit(index)} className="text-yellow-500 hover:text-yellow-600">
                    <FaPen />
                  </button>
                  <button onClick={() => handleDelete(index)} className="text-red-500 hover:text-red-600">
                    <FaTrash />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Add New Report Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-40 flex justify-center items-center z-50">
          <div className="bg-white p-8 rounded-xl shadow-2xl w-[500px] relative">
            <button
              className="absolute top-3 right-3 text-gray-600 hover:text-gray-900"
              onClick={() => setIsModalOpen(false)}
            >
              <FaTimes size={20} />
            </button>
            <h2 className="text-xl font-bold mb-6 text-center">Add New Report</h2>
            <div className="grid grid-cols-2 gap-4">
              <input
                type="text"
                name="reportTitle"
                placeholder="Report Title"
                value={newReport.reportTitle}
                onChange={handleInputChange}
                className="p-3 border rounded"
              />
              <input
                type="date"
                name="date"
                value={newReport.date}
                onChange={handleInputChange}
                className="p-3 border rounded"
              />
              <input
                type="text"
                name="generatedBy"
                placeholder="Generated By"
                value={newReport.generatedBy}
                onChange={handleInputChange}
                className="p-3 border rounded"
              />
              <select
                name="status"
                value={newReport.status}
                onChange={handleInputChange}
                className="p-3 border rounded col-span-2"
              >
                <option value="">Select Status</option>
                <option value="Completed">Completed</option>
                <option value="In Progress">In Progress</option>
                <option value="Pending">Pending</option>
              </select>
            </div>
            <div className="flex justify-end gap-4 mt-6">
              <button
                onClick={() => setIsModalOpen(false)}
                className="px-5 py-2 bg-gray-400 hover:bg-gray-500 text-white rounded"
              >
                Cancel
              </button>
              <button
                onClick={handleAddReport}
                className="px-5 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded"
              >
                Save
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ReportsList;
